name: stadssurr_env
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=21.1.4
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libuv=1.51.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nodejs=24.4.1
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cryptography==46.0.1
      - dnspython==2.8.0
      - ecdsa==0.19.1
      - email-validator==2.3.0
      - fastapi==0.118.0
      - h11==0.16.0
      - httptools==0.6.4
      - idna==3.10
      - json5==0.12.1
      - passlib==1.7.4
      - pyasn1==0.6.1
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pyproj==3.7.1
      - python-dotenv==1.1.1
      - python-jose==3.5.0
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - requests==2.32.5
      - rsa==4.9.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.43
      - starlette==0.48.0
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
prefix: /Users/willi/miniconda3/envs/node_v2
